/* Automatically generated by './build/bin/build-entry.js' */

import WnAvatar from "../components/wn-avatar/lib/index.js";
import WnDemoTag from "../components/wn-demo-tag/lib/index.js";
// import WnPatientCard from '../components/wn-patient-card/index.js'
import WnTag from "../components/wn-tag/lib/index.js";
import WnTitle from "../components/wn-title/lib/index.js";

const components = [
  WnAvatar,
  WnDemoTag,
  // WnPatientCard,
  WnTag,
  WnTitle
];

const install = function(Vue, opts = {}) {
  if (Vue.WIN_INSTALLED) return; // 只install一次，不同版本问题
  components.forEach(component => {
    if (component.notVueObj) {
      return;
    }
    Vue.component(component.name, component);
  });
  // api方式挂载
  // Vue.prototype.$demo = demo.popup;

  Object.defineProperty(Vue, "WIN_INSTALLED", {
    configurable: false,
    value: true,
    enumerable: false,
    writable: false
  });
};

/* istanbul ignore if */
if (typeof window !== "undefined" && window.Vue) {
  install(window.Vue);
}

export default {
  version: "1.0.0",
  install,
  WnAvatar,
  WnDemoTag,
  // WnPatientCard,
  WnTag,
  WnTitle
};
