/* Automatically generated by './build/bin/build-entry.js' */

import WnDemo from '../components/wn-demo/lib/index.js'

const components = [
  WnDemo
]

const install = function (Vue, opts = {}) {
  if (Vue.WIN_INSTALLED) return // 只install一次，不同版本问题
  components.forEach(component => {
    if (component.notVueObj) {
      return
    }
    Vue.component(component.name, component)
  })
  // api方式挂载
  // Vue.prototype.$demo = demo.popup;

  Object.defineProperty(Vue, 'WIN_INSTALLED', {
    configurable: false,
    value: true,
    enumerable: false,
    writable: false
  })
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  version: '1.0.0',
  install,
  WnDemo
}
